name: granger
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - gpy
  - matplotlib
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - pytorch
  - statsmodels
  - tigramite
  - numba
  - dcor
  - jupyter
